services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: missciftlik
      MYSQL_ROOT_PASSWORD: mypassword1
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: mypassword1
    ports:
      - "8080:80"
